version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
      - image: circleci/redis:latest
      - image: circleci/postgres:9.6.2-alpine
      - image: circleci/mongo:4.4.3

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            ls -all
            cd wheels
            ls -all
            cd ..
            cat requirements.txt
            pip install -r requirements.txt
            pip install -r requirements-test.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            flake8
            isort ./mongo-to-sql --check --diff
            coverage run -m pytest --pyargs mongo_to_sql_tests
            coverage xml -i
    
      - codecov/upload:
          file: ./coverage.xml

  
  
  
  
  
  
  
  